// flow-typed signature: fd27eb665b23179961a24a8d22e0c96b
// flow-typed version: <<STUB>>/babel-plugin-typecheck_v3.9.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-typecheck'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-typecheck' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-typecheck/lib-checked/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/lib/inferers' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/lib/old_index' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/lib/type-checks' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/lib/types' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/src/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test-polyfill' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/any-return-value' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/array-type-annotation' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/arrow-function-2' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/arrow-function' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/assignment-expression' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/async-function-return-promise' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/async-function' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/async-method' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bad-array-return-value' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bad-async-function' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bad-binary-return-value' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bad-class-getter' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bad-class-setter' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bad-conditional-expression' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bad-conditional-return-value' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bad-const-tracking' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bad-default-arguments' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bad-function-return-value' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bad-generators-return' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bad-generators' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bad-infer-nested-member-expression-from-typealias' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bad-iterable-type' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bad-iterable' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bad-map-values' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bad-object-method-arrow' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bad-object-method' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bad-object-properties' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bad-rest-params-2' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bad-rest-params' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bad-return-value' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bad-string-literal-annotations' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bad-tuples' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/binary-return-value' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/boolean-literal-annotations' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bug-107-type-alias' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bug-108-default-value' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bug-30-conditional-return' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bug-48-export-star' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bug-59-type-annotation-in-loop-again' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bug-59-type-annotation-in-loop' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bug-62-default-params' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bug-68-return-string-literal' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bug-7-class-support' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bug-71-cannot-iterate-void' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bug-76-cannot-read-property-name-of-undefined' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bug-78-not-type-checked-array' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bug-8-class-support' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bug-82-too-much-inference' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bug-83-spread-object' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bug-87-bad-check' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bug-96-iterate-array' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bug-98-false-positive-destructuring-expression' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bug-98-false-positive-destructuring' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bug-xxx-assignment-expression' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bug-xxx-export' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bug-xxx-literal-return' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/bug-xxx-method-params' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/callexpr-return-value' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/class-annotation' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/class-getter' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/class-implements' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/class-method' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/class-properties-complex' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/class-properties' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/class-setter' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/class-type-params' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/complex-object-types' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/conditional-expression' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/conditional-return-value' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/const-tracking-with-new-extended' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/const-tracking-with-new' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/const-tracking' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/default-arguments' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/enum' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/export-class' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/export-type' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/export-typed-var' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/fancy-generic-function' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/float32' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/float64' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/generators-with-next' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/generators' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/generic-function' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/import-multiple-types' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/import-type' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/indexers' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/infer-member-expression-from-object' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/infer-member-expression-from-typealias' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/infer-member-expression' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/infer-nested-member-expression-from-typealias' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/int16' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/int32' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/int8' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/interface-extends' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/interface-multi-extends' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/interface' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/intersection' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/iterable' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/logical-expression' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/logical-or-expression' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/map-contents' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/map-keys' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/map-values' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/missing-return-with-mixed' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/missing-return-with-nullable' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/missing-return' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/mixed-return-value' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/multiple-arguments' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/nested-object-types' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/new' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/numeric-literal-annotations' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/object-indexer-basic' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/object-indexer-mixed' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/object-method' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/object-pattern-complex' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/object-pattern' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/object-properties-function' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/object-properties' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/optional-arguments' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/optional-properties' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/poly-args' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/pragma-ignore-file' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/pragma-ignore-statement' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/pragma-opt-in' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/qualified-types' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/react-decorator' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/react-parameterized' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/react-proptypes' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/rest-params-array' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/rest-params' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/return-object-types' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/return-regexp' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/set-entries' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/string-arguments' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/string-literal-annotations' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/symbols' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/tuples-assignment-expression' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/tuples' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/type-aliases' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/typeof-class' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/typeof' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/uint16' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/uint32' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/uint8' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/var-declarations-2' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/fixtures/var-declarations' {
  declare module.exports: any;
}

declare module 'babel-plugin-typecheck/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-typecheck/lib-checked/index.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/lib-checked/index'>;
}
declare module 'babel-plugin-typecheck/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/lib/index'>;
}
declare module 'babel-plugin-typecheck/lib/inferers.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/lib/inferers'>;
}
declare module 'babel-plugin-typecheck/lib/old_index.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/lib/old_index'>;
}
declare module 'babel-plugin-typecheck/lib/type-checks.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/lib/type-checks'>;
}
declare module 'babel-plugin-typecheck/lib/types.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/lib/types'>;
}
declare module 'babel-plugin-typecheck/src/index.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/src/index'>;
}
declare module 'babel-plugin-typecheck/test-polyfill.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test-polyfill'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/any-return-value.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/any-return-value'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/array-type-annotation.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/array-type-annotation'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/arrow-function-2.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/arrow-function-2'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/arrow-function.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/arrow-function'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/assignment-expression.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/assignment-expression'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/async-function-return-promise.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/async-function-return-promise'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/async-function.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/async-function'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/async-method.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/async-method'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bad-array-return-value.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bad-array-return-value'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bad-async-function.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bad-async-function'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bad-binary-return-value.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bad-binary-return-value'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bad-class-getter.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bad-class-getter'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bad-class-setter.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bad-class-setter'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bad-conditional-expression.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bad-conditional-expression'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bad-conditional-return-value.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bad-conditional-return-value'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bad-const-tracking.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bad-const-tracking'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bad-default-arguments.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bad-default-arguments'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bad-function-return-value.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bad-function-return-value'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bad-generators-return.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bad-generators-return'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bad-generators.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bad-generators'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bad-infer-nested-member-expression-from-typealias.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bad-infer-nested-member-expression-from-typealias'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bad-iterable-type.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bad-iterable-type'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bad-iterable.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bad-iterable'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bad-map-values.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bad-map-values'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bad-object-method-arrow.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bad-object-method-arrow'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bad-object-method.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bad-object-method'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bad-object-properties.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bad-object-properties'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bad-rest-params-2.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bad-rest-params-2'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bad-rest-params.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bad-rest-params'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bad-return-value.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bad-return-value'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bad-string-literal-annotations.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bad-string-literal-annotations'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bad-tuples.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bad-tuples'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/binary-return-value.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/binary-return-value'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/boolean-literal-annotations.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/boolean-literal-annotations'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bug-107-type-alias.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bug-107-type-alias'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bug-108-default-value.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bug-108-default-value'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bug-30-conditional-return.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bug-30-conditional-return'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bug-48-export-star.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bug-48-export-star'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bug-59-type-annotation-in-loop-again.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bug-59-type-annotation-in-loop-again'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bug-59-type-annotation-in-loop.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bug-59-type-annotation-in-loop'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bug-62-default-params.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bug-62-default-params'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bug-68-return-string-literal.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bug-68-return-string-literal'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bug-7-class-support.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bug-7-class-support'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bug-71-cannot-iterate-void.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bug-71-cannot-iterate-void'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bug-76-cannot-read-property-name-of-undefined.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bug-76-cannot-read-property-name-of-undefined'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bug-78-not-type-checked-array.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bug-78-not-type-checked-array'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bug-8-class-support.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bug-8-class-support'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bug-82-too-much-inference.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bug-82-too-much-inference'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bug-83-spread-object.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bug-83-spread-object'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bug-87-bad-check.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bug-87-bad-check'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bug-96-iterate-array.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bug-96-iterate-array'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bug-98-false-positive-destructuring-expression.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bug-98-false-positive-destructuring-expression'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bug-98-false-positive-destructuring.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bug-98-false-positive-destructuring'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bug-xxx-assignment-expression.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bug-xxx-assignment-expression'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bug-xxx-export.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bug-xxx-export'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bug-xxx-literal-return.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bug-xxx-literal-return'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/bug-xxx-method-params.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/bug-xxx-method-params'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/callexpr-return-value.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/callexpr-return-value'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/class-annotation.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/class-annotation'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/class-getter.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/class-getter'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/class-implements.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/class-implements'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/class-method.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/class-method'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/class-properties-complex.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/class-properties-complex'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/class-properties.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/class-properties'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/class-setter.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/class-setter'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/class-type-params.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/class-type-params'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/complex-object-types.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/complex-object-types'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/conditional-expression.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/conditional-expression'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/conditional-return-value.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/conditional-return-value'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/const-tracking-with-new-extended.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/const-tracking-with-new-extended'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/const-tracking-with-new.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/const-tracking-with-new'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/const-tracking.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/const-tracking'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/default-arguments.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/default-arguments'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/enum.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/enum'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/export-class.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/export-class'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/export-type.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/export-type'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/export-typed-var.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/export-typed-var'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/fancy-generic-function.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/fancy-generic-function'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/float32.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/float32'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/float64.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/float64'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/generators-with-next.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/generators-with-next'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/generators.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/generators'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/generic-function.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/generic-function'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/import-multiple-types.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/import-multiple-types'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/import-type.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/import-type'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/indexers.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/indexers'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/infer-member-expression-from-object.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/infer-member-expression-from-object'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/infer-member-expression-from-typealias.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/infer-member-expression-from-typealias'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/infer-member-expression.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/infer-member-expression'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/infer-nested-member-expression-from-typealias.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/infer-nested-member-expression-from-typealias'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/int16.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/int16'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/int32.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/int32'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/int8.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/int8'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/interface-extends.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/interface-extends'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/interface-multi-extends.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/interface-multi-extends'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/interface.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/interface'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/intersection.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/intersection'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/iterable.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/iterable'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/logical-expression.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/logical-expression'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/logical-or-expression.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/logical-or-expression'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/map-contents.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/map-contents'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/map-keys.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/map-keys'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/map-values.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/map-values'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/missing-return-with-mixed.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/missing-return-with-mixed'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/missing-return-with-nullable.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/missing-return-with-nullable'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/missing-return.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/missing-return'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/mixed-return-value.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/mixed-return-value'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/multiple-arguments.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/multiple-arguments'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/nested-object-types.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/nested-object-types'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/new.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/new'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/numeric-literal-annotations.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/numeric-literal-annotations'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/object-indexer-basic.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/object-indexer-basic'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/object-indexer-mixed.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/object-indexer-mixed'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/object-method.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/object-method'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/object-pattern-complex.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/object-pattern-complex'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/object-pattern.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/object-pattern'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/object-properties-function.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/object-properties-function'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/object-properties.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/object-properties'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/optional-arguments.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/optional-arguments'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/optional-properties.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/optional-properties'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/poly-args.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/poly-args'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/pragma-ignore-file.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/pragma-ignore-file'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/pragma-ignore-statement.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/pragma-ignore-statement'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/pragma-opt-in.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/pragma-opt-in'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/qualified-types.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/qualified-types'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/react-decorator.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/react-decorator'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/react-parameterized.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/react-parameterized'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/react-proptypes.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/react-proptypes'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/rest-params-array.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/rest-params-array'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/rest-params.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/rest-params'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/return-object-types.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/return-object-types'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/return-regexp.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/return-regexp'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/set-entries.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/set-entries'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/string-arguments.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/string-arguments'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/string-literal-annotations.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/string-literal-annotations'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/symbols.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/symbols'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/tuples-assignment-expression.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/tuples-assignment-expression'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/tuples.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/tuples'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/type-aliases.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/type-aliases'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/typeof-class.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/typeof-class'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/typeof.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/typeof'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/uint16.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/uint16'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/uint32.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/uint32'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/uint8.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/uint8'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/var-declarations-2.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/var-declarations-2'>;
}
declare module 'babel-plugin-typecheck/test/fixtures/var-declarations.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/fixtures/var-declarations'>;
}
declare module 'babel-plugin-typecheck/test/index.js' {
  declare module.exports: $Exports<'babel-plugin-typecheck/test/index'>;
}
