// flow-typed signature: 970da97d698603d30a4d71022aa50a3b
// flow-typed version: <<STUB>>/debounce_v^1.0.2/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'debounce'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'debounce' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'debounce/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'debounce/index' {
  declare module.exports: $Exports<'debounce'>;
}
declare module 'debounce/index.js' {
  declare module.exports: $Exports<'debounce'>;
}
declare module 'debounce/test.js' {
  declare module.exports: $Exports<'debounce/test'>;
}
