// flow-typed signature: 27d78de94be2e1a734f7adfa7816be18
// flow-typed version: <<STUB>>/debounce-promise_v^3.0.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'debounce-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'debounce-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'debounce-promise/dist/index' {
  declare module.exports: any;
}

declare module 'debounce-promise/example' {
  declare module.exports: any;
}

declare module 'debounce-promise/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'debounce-promise/dist/index.js' {
  declare module.exports: $Exports<'debounce-promise/dist/index'>;
}
declare module 'debounce-promise/example.js' {
  declare module.exports: $Exports<'debounce-promise/example'>;
}
declare module 'debounce-promise/index' {
  declare module.exports: $Exports<'debounce-promise'>;
}
declare module 'debounce-promise/index.js' {
  declare module.exports: $Exports<'debounce-promise'>;
}
declare module 'debounce-promise/test/index.js' {
  declare module.exports: $Exports<'debounce-promise/test/index'>;
}
