// flow-typed signature: 36a8eec5dfb86c97f3b159ab679413d3
// flow-typed version: <<STUB>>/react-datepicker_v^0.48.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-datepicker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-datepicker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-datepicker/dist/react-datepicker' {
  declare module.exports: any;
}

declare module 'react-datepicker/dist/react-datepicker.min' {
  declare module.exports: any;
}

declare module 'react-datepicker/lib/calendar' {
  declare module.exports: any;
}

declare module 'react-datepicker/lib/date_utils' {
  declare module.exports: any;
}

declare module 'react-datepicker/lib/datepicker' {
  declare module.exports: any;
}

declare module 'react-datepicker/lib/day' {
  declare module.exports: any;
}

declare module 'react-datepicker/lib/month_dropdown_options' {
  declare module.exports: any;
}

declare module 'react-datepicker/lib/month_dropdown' {
  declare module.exports: any;
}

declare module 'react-datepicker/lib/month' {
  declare module.exports: any;
}

declare module 'react-datepicker/lib/tether_component' {
  declare module.exports: any;
}

declare module 'react-datepicker/lib/week_number' {
  declare module.exports: any;
}

declare module 'react-datepicker/lib/week' {
  declare module.exports: any;
}

declare module 'react-datepicker/lib/year_dropdown_options' {
  declare module.exports: any;
}

declare module 'react-datepicker/lib/year_dropdown' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-datepicker/dist/react-datepicker.js' {
  declare module.exports: $Exports<'react-datepicker/dist/react-datepicker'>;
}
declare module 'react-datepicker/dist/react-datepicker.min.js' {
  declare module.exports: $Exports<'react-datepicker/dist/react-datepicker.min'>;
}
declare module 'react-datepicker/lib/calendar.js' {
  declare module.exports: $Exports<'react-datepicker/lib/calendar'>;
}
declare module 'react-datepicker/lib/date_utils.js' {
  declare module.exports: $Exports<'react-datepicker/lib/date_utils'>;
}
declare module 'react-datepicker/lib/datepicker.js' {
  declare module.exports: $Exports<'react-datepicker/lib/datepicker'>;
}
declare module 'react-datepicker/lib/day.js' {
  declare module.exports: $Exports<'react-datepicker/lib/day'>;
}
declare module 'react-datepicker/lib/month_dropdown_options.js' {
  declare module.exports: $Exports<'react-datepicker/lib/month_dropdown_options'>;
}
declare module 'react-datepicker/lib/month_dropdown.js' {
  declare module.exports: $Exports<'react-datepicker/lib/month_dropdown'>;
}
declare module 'react-datepicker/lib/month.js' {
  declare module.exports: $Exports<'react-datepicker/lib/month'>;
}
declare module 'react-datepicker/lib/tether_component.js' {
  declare module.exports: $Exports<'react-datepicker/lib/tether_component'>;
}
declare module 'react-datepicker/lib/week_number.js' {
  declare module.exports: $Exports<'react-datepicker/lib/week_number'>;
}
declare module 'react-datepicker/lib/week.js' {
  declare module.exports: $Exports<'react-datepicker/lib/week'>;
}
declare module 'react-datepicker/lib/year_dropdown_options.js' {
  declare module.exports: $Exports<'react-datepicker/lib/year_dropdown_options'>;
}
declare module 'react-datepicker/lib/year_dropdown.js' {
  declare module.exports: $Exports<'react-datepicker/lib/year_dropdown'>;
}
